apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

repositories {
    mavenCentral()
}

android {
    compileSdk 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.moblico.sdk'
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api 'com.google.code.gson:gson:2.9.1'
    implementation 'androidx.core:core:1.9.0'
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.Moblico'
            artifactId = 'MoblicoSDK-Android'
            version = '1.0-SNAPSHOT'

            afterEvaluate {
                from components.findByName('release')
            }
        }
    }
}